name 'policy_linux_mysql'
maintainer 'aliasgar'
maintainer_email 'achoolawala@gmail.com'
license 'all_rights'
description 'Restarts httpd, tomcat7, mysqld services'
long_description 'Restarts httpd, tomcat7, mysqld services'
version '0.1.0'
